version: '3'
services:
  portfolio:
    build: ./
    ports:
      - 3000:3000
  nginx:
    build: ./nginx
    ports:
      - 80:80
  portfolio-dev:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./:/app
    ports:
      - 3000:3000
